# -*- coding: utf-8 -*-
"""EEG.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1KQyt7HIIieXrIJRv2bzPxCTuFfu7uzHN

# **Emotion Classification _ EEG Signal _ An easy projects_ Shayan**

## Document

This notebook implements a complete deep learning pipeline for emotion classification using EEG (Electroencephalogram) signals. The dataset, containing multiple numerical EEG features and corresponding emotion labels, is first imported and preprocessed through several steps including label encoding, standardization, and data reshaping to ensure compatibility with different neural architectures. The features are normalized to zero mean and unit variance, and the dataset is divided into training and testing subsets to allow fair performance evaluation.

Three neural network models are designed and compared: a one-dimensional Convolutional Neural Network (CNN), a fully connected Artificial Neural Network (ANN), and a Long Short-Term Memory (LSTM) model. The CNN captures local spatial dependencies within EEG features using convolutional and pooling layers, while the ANN learns global feature relationships through dense connections. The LSTM model focuses on temporal dynamics, learning long-term dependencies across sequential EEG patterns. Each model employs regularization techniques such as Batch Normalization and Dropout to prevent overfitting, and all are trained using the Adam optimizer with categorical cross-entropy loss.

After training, model performance is evaluated on the test set using accuracy as the primary metric. The notebook thereby provides a comparative framework to assess how different deep learning architectures interpret EEG signals for emotion recognition tasks, highlighting their strengths in handling spatial, global, and temporal feature representations.

## Initials
"""

from google.colab import drive
drive.mount('/content/drive', force_remount=True)

import numpy as np
import pandas as pd

import pandas as pd
from sklearn.preprocessing import StandardScaler, LabelEncoder
from sklearn.model_selection import train_test_split
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Conv1D, MaxPooling1D, Flatten, Dense, Dropout, BatchNormalization,LSTM

df = pd.read_csv('/content/drive/MyDrive/Emotion_Classification_EEG_Data_.csv')

df.head()

#a total of 2132 rows and 2549 columns shoule be present
df.shape

"""##  Preproceesing"""

# 📌 Separate features & labels
x = df.iloc[:, :-1].values  # EEG features (all columns except last)
y = df.iloc[:, -1].values   # Target labels (emotion category)

# Encoding labels (Converting text labels to numbers)
label_encoder = LabelEncoder()
y = label_encoder.fit_transform(y)

#Normalizing EEG feature values
scaler = StandardScaler()
x = scaler.fit_transform(x)

#Reshape data for CNN input (CNN expects 3D input: samples, timesteps, features)
x = np.expand_dims(x, axis=2)  # Shape: (2132, 2548, 1)

#Splitting into train and test
xtrain, xtest, ytrain, ytest = train_test_split(x, y, test_size=0.2, random_state=42)

"""##  CNN"""

model = Sequential([
    Conv1D(filters=64, kernel_size=3, activation='relu', input_shape=(x.shape[1], 1)),
    BatchNormalization(),
    MaxPooling1D(pool_size=2),

    Conv1D(filters=128, kernel_size=3, activation='relu'),
    BatchNormalization(),
    MaxPooling1D(pool_size=2),

    Flatten(),
    Dense(128, activation='relu'),
    Dropout(0.3),
    Dense(64, activation='relu'),
    Dropout(0.3),
    Dense(len(np.unique(y)), activation='softmax')  # Output layer for classification
])

model.compile(optimizer='adam', loss='sparse_categorical_crossentropy', metrics=['accuracy'])

# 📌 Train the model
history = model.fit(xtrain, ytrain, epochs=30, batch_size=32, validation_data=(xtest, ytest))

test_loss, test_acc = model.evaluate(xtest, ytest)
print(f"Test Accuracy: {test_acc:.4f}")

"""TEST ACC = 98.59%

## ANN
"""

model1 = Sequential([
    Dense(512, activation='relu', input_shape=(x.shape[1],)),  # 🔹 Input layer: 2548 neurons
    BatchNormalization(),
    Dropout(0.3),

    Dense(256, activation='relu'),  # Hidden layer 1
    BatchNormalization(),
    Dropout(0.3),

    Dense(128, activation='relu'),  # Hidden layer 2
    Dropout(0.3),

    Dense(len(np.unique(y)), activation='softmax')  # Output layer for classification
])

model1.compile(optimizer='adam', loss='sparse_categorical_crossentropy', metrics=['accuracy'])

model1.fit(xtrain, ytrain, epochs=30, batch_size=32, validation_data=(xtest, ytest))

test_loss, test_acc = model1.evaluate(xtest, ytest)
print(f"Test Accuracy: {test_acc:.4f}")

"""TEST ACC: 97.66%

##  LSTM
"""

model2 = Sequential([
    LSTM(128, return_sequences=True, input_shape=(x.shape[1], 1)),  # First LSTM layer
    BatchNormalization(),
    Dropout(0.3),

    LSTM(64, return_sequences=False),  # Second LSTM layer
    BatchNormalization(),
    Dropout(0.3),

    Dense(64, activation='relu'),
    Dropout(0.3),

    Dense(len(np.unique(y)), activation='softmax')  # Output layer for classification
])

model2.compile(optimizer='adam', loss='sparse_categorical_crossentropy', metrics=['accuracy'])

model2.fit(xtrain, ytrain, epochs=30, batch_size=32, validation_data=(xtest, ytest))

test_loss, test_acc = model2.evaluate(xtest, ytest)
print(f"Test Accuracy: {test_acc:.4f}")

"""TEST ACC: 91.57%

## Question: shayanrokhva1999@gmail.com
"""